import Foundation
import Accelerate

/// 4× polyphase oversampling around a memoryless nonlinearity (here, tanh).
/// Each input sample is upsampled (zero-stuff + lowpass), saturated with
/// `tanh(drive · x)` at the oversampled rate, then downsampled (lowpass +
/// decimate). Without this wrapper, tanh's high-order harmonics — generated by
/// the curve's odd-power expansion — fold back into the audible band as harsh
/// aliasing the moment drive is pushed.
///
/// 128 taps total (32 per phase) with a Hamming window; the lowpass cutoff is
/// at the original Nyquist so the same FIR rejects images on the upsample side
/// and would-be aliases on the downsample side. Group delay ≈ 16 input samples
/// (~0.3 ms at 48 kHz) — inaudible.
///
/// One instance per channel. Everything is preallocated; the audio thread does
/// no allocations.
final class SaturatorOversampler {
    static let osFactor = 4
    static let phaseTaps = 32
    static let totalTaps = phaseTaps * osFactor   // 128

    // The two static tables are filled once at first access and only read
    // thereafter. `nonisolated(unsafe)` tells Swift 6 we vouch for that — the
    // pointer type isn't Sendable on its own.

    /// Shared lowpass FIR. Used directly by the downsampler.
    nonisolated(unsafe) private static let lowpass: UnsafeMutablePointer<Float> = makeLowpass()
    /// Polyphase decomposition for the upsampler:
    /// `phasesUp[p * phaseTaps + k] = lowpass[p + osFactor * k]`, pre-multiplied
    /// by `osFactor` to compensate the zero-stuffing average loss.
    nonisolated(unsafe) private static let phasesUp: UnsafeMutablePointer<Float> = makePhases()

    private static func makeLowpass() -> UnsafeMutablePointer<Float> {
        let omegaC = Double.pi / Double(osFactor)
        let center = Double(totalTaps - 1) / 2.0
        var h = [Double](repeating: 0, count: totalTaps)
        var sum: Double = 0
        for n in 0..<totalTaps {
            let m = Double(n) - center
            let sinc = (m == 0) ? omegaC / .pi : sin(omegaC * m) / (.pi * m)
            let hamming = 0.54 - 0.46 * cos(2 * .pi * Double(n) / Double(totalTaps - 1))
            let c = sinc * hamming
            h[n] = c
            sum += c
        }
        let ptr = UnsafeMutablePointer<Float>.allocate(capacity: totalTaps)
        for n in 0..<totalTaps { ptr[n] = Float(h[n] / sum) }
        return ptr
    }

    private static func makePhases() -> UnsafeMutablePointer<Float> {
        let ptr = UnsafeMutablePointer<Float>.allocate(capacity: osFactor * phaseTaps)
        let gain = Float(osFactor)
        for p in 0..<osFactor {
            for k in 0..<phaseTaps {
                ptr[p * phaseTaps + k] = gain * lowpass[p + osFactor * k]
            }
        }
        return ptr
    }

    private let inputDelay: UnsafeMutablePointer<Float>
    private let osDelay: UnsafeMutablePointer<Float>

    init() {
        inputDelay = .allocate(capacity: Self.phaseTaps)
        osDelay = .allocate(capacity: Self.totalTaps)
        inputDelay.initialize(repeating: 0, count: Self.phaseTaps)
        osDelay.initialize(repeating: 0, count: Self.totalTaps)
    }

    deinit {
        inputDelay.deallocate()
        osDelay.deallocate()
    }

    func reset() {
        inputDelay.update(repeating: 0, count: Self.phaseTaps)
        osDelay.update(repeating: 0, count: Self.totalTaps)
    }

    /// Process one sample → one sample. Equivalent to `tanh(drive · x)` but
    /// without the in-band aliasing that the raw nonlinearity introduces.
    func processSample(_ x: Float, drive: Float) -> Float {
        let pt = Self.phaseTaps
        let tt = Self.totalTaps
        let osf = Self.osFactor
        let phUp = Self.phasesUp
        let lp = Self.lowpass

        // Insert x at index 0 of the input delay line (most-recent-first).
        memmove(inputDelay.advanced(by: 1), inputDelay,
                (pt - 1) * MemoryLayout<Float>.stride)
        inputDelay[0] = x

        // Four polyphase dot products in a single pass through the delay line —
        // four independent accumulators auto-vectorize cleanly on Apple Silicon.
        var a0: Float = 0, a1: Float = 0, a2: Float = 0, a3: Float = 0
        for k in 0..<pt {
            let xk = inputDelay[k]
            a0 += phUp[0 * pt + k] * xk
            a1 += phUp[1 * pt + k] * xk
            a2 += phUp[2 * pt + k] * xk
            a3 += phUp[3 * pt + k] * xk
        }
        // tanh at the oversampled rate. Phase 0 is earliest in time, phase 3
        // latest.
        let s0 = tanhf(drive * a0)
        let s1 = tanhf(drive * a1)
        let s2 = tanhf(drive * a2)
        let s3 = tanhf(drive * a3)

        // Push the 4 new oversampled samples into the downsample delay line,
        // most-recent-first.
        memmove(osDelay.advanced(by: osf), osDelay,
                (tt - osf) * MemoryLayout<Float>.stride)
        osDelay[0] = s3
        osDelay[1] = s2
        osDelay[2] = s1
        osDelay[3] = s0

        // Downsample = single FIR convolution at the oversampled rate; take one
        // sample per L oversampled inputs.
        var down: Float = 0
        vDSP_dotpr(lp, 1, osDelay, 1, &down, vDSP_Length(tt))
        return down
    }
}
